// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: OTR_AMOLED_UITEST

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Main
void ui_Main_screen_init(void);
void ui_event_Main(lv_event_t * e);
lv_obj_t * ui_Main;
lv_obj_t * ui_Main_TopPanel;
lv_obj_t * ui_Main_TopPanelBattery;
void ui_event_Main_TopPanelScan(lv_event_t * e);
lv_obj_t * ui_Main_TopPanelScan;
void ui_event_Main_TopPanelButtonSettings(lv_event_t * e);
lv_obj_t * ui_Main_TopPanelButtonSettings;
void ui_event_Main_TopPanelButtonTime(lv_event_t * e);
lv_obj_t * ui_Main_TopPanelButtonTime;
lv_obj_t * ui_Main_TopPanelTime;
lv_obj_t * ui_Main_Label_Title;
lv_obj_t * ui_Main_Label_RFID;
lv_obj_t * ui_Main_LabelBottom;
lv_obj_t * ui_Main_Panel1;
lv_obj_t * ui_Main_Counter;
lv_obj_t * ui_Main_Label_Session;
lv_obj_t * ui_Main_Label_Location;
lv_obj_t * ui_Main_Label_VisualID;


// SCREEN: ui_Time
void ui_Time_screen_init(void);
void ui_event_Time(lv_event_t * e);
lv_obj_t * ui_Time;
lv_obj_t * ui_Time_Label_Title;
lv_obj_t * ui_Time_Label_Date;
lv_obj_t * ui_Time_Label_Time;
void ui_event_Time_SetTime(lv_event_t * e);
lv_obj_t * ui_Time_SetTime;
lv_obj_t * ui_Time_Label4;
void ui_event_Time_Sync(lv_event_t * e);
lv_obj_t * ui_Time_Sync;
lv_obj_t * ui_Time_Label1;


// SCREEN: ui_SetTime
void ui_SetTime_screen_init(void);
void ui_event_SetTime(lv_event_t * e);
lv_obj_t * ui_SetTime;
lv_obj_t * ui_SetTime_TabView;
lv_obj_t * ui_SetTime_TabPageTime;
lv_obj_t * ui_Time_RollerHour;
lv_obj_t * ui_Time_RollerMinute;
lv_obj_t * ui_Time_RollerAMPM;
void ui_event_SetTime_ButtonManual(lv_event_t * e);
lv_obj_t * ui_SetTime_ButtonManual;
lv_obj_t * ui_SetTime_Label5;
lv_obj_t * ui_SetTime_TabPageDate;
void ui_event_SetDate_ButtonManual(lv_event_t * e);
lv_obj_t * ui_SetDate_ButtonManual;
lv_obj_t * ui_SetDateLabel;
lv_obj_t * ui_Date_RollerDay;
void ui_event_Date_RollerYear(lv_event_t * e);
lv_obj_t * ui_Date_RollerYear;
void ui_event_Date_RollerMonth(lv_event_t * e);
lv_obj_t * ui_Date_RollerMonth;


// SCREEN: ui_Session
void ui_Session_screen_init(void);
void ui_event_Session(lv_event_t * e);
lv_obj_t * ui_Session;
lv_obj_t * ui_Session_NewButton;
lv_obj_t * ui_SessionNewButton_Label;
lv_obj_t * ui_Session_ContinueButton;
lv_obj_t * ui_SessionContinueButton_Label;
lv_obj_t * ui_Session_Roller1;


// SCREEN: ui_Tagging
void ui_Tagging_screen_init(void);
lv_obj_t * ui_Tagging;
lv_obj_t * ui_AddAnimal_Accept;
lv_obj_t * ui_AddAnimal_Label1;
lv_obj_t * ui_AddAnimal_Label2;
lv_obj_t * ui_AddAnimal_Location;
lv_obj_t * ui_AddAnimal_Group;
lv_obj_t * ui_AddAnimal_Switch1;
lv_obj_t * ui_AddAnimal_Label3;
lv_obj_t * ui_AddAnimal_RFID;
lv_obj_t * ui_AddAnimal_Label5;
lv_obj_t * ui_AddAnimal_Treatment;


// SCREEN: ui_Settings
void ui_Settings_screen_init(void);
void ui_event_Settings(lv_event_t * e);
lv_obj_t * ui_Settings;
lv_obj_t * ui_Settings_Label_Top;
lv_obj_t * ui_Settings_TabView;
lv_obj_t * ui_Settings_TabPageFiles;
lv_obj_t * ui_Settings_TextAreaFiles;
lv_obj_t * ui_Settings_TabPageStorage;
lv_obj_t * ui_Settings_TextAreaStorage;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_turn_left_200dp_1f1f1f_fill0_wght700_grad0_opsz[1] = {&ui_img_turn_left_200dp_1f1f1f_fill0_wght700_grad0_opsz48_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Main(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        mainScreenLoaded(e);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Session, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Session_screen_init);
    }
}
void ui_event_Main_TopPanelScan(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        tetherClicked(e);
    }
}
void ui_event_Main_TopPanelButtonSettings(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Settings, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Settings_screen_init);
    }
}
void ui_event_Main_TopPanelButtonTime(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Time, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Time_screen_init);
    }
}
void ui_event_Time(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Main, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 200, 0, &ui_Main_screen_init);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        timeScreenLoaded(e);
    }
}
void ui_event_Time_SetTime(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SetTime, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_SetTime_screen_init);
    }
}
void ui_event_Time_Sync(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Main, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Main_screen_init);
    }
}
void ui_event_SetTime(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        SetTimeScreenLoaded(e);
    }
}
void ui_event_SetTime_ButtonManual(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        setTimeManual(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Time, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Time_screen_init);
    }
}
void ui_event_SetDate_ButtonManual(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        setTimeManual(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Time, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Time_screen_init);
    }
}
void ui_event_Date_RollerYear(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        roller_update(e);
    }
}
void ui_event_Date_RollerMonth(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        roller_update(e);
    }
}
void ui_event_Session(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Main, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Main_screen_init);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        sessionScreenLoaded(e);
    }
}
void ui_event_Settings(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        settingsScreenLoaded(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Main_screen_init();
    ui_Time_screen_init();
    ui_SetTime_screen_init();
    ui_Session_screen_init();
    ui_Tagging_screen_init();
    ui_Settings_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Main);
}
