// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: OTR_AMOLED_UITEST

#ifndef _OTR_AMOLED_UITEST_UI_H
#define _OTR_AMOLED_UITEST_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_Main
void ui_Main_screen_init(void);
void ui_event_Main(lv_event_t * e);
extern lv_obj_t * ui_Main;
extern lv_obj_t * ui_Main_TopPanel;
extern lv_obj_t * ui_Main_TopPanelBattery;
void ui_event_Main_TopPanelScan(lv_event_t * e);
extern lv_obj_t * ui_Main_TopPanelScan;
void ui_event_Main_TopPanelButtonSettings(lv_event_t * e);
extern lv_obj_t * ui_Main_TopPanelButtonSettings;
void ui_event_Main_TopPanelButtonTime(lv_event_t * e);
extern lv_obj_t * ui_Main_TopPanelButtonTime;
extern lv_obj_t * ui_Main_TopPanelTime;
extern lv_obj_t * ui_Main_Label_Title;
extern lv_obj_t * ui_Main_Label_RFID;
extern lv_obj_t * ui_Main_LabelBottom;
void ui_event_Main_Panel1(lv_event_t * e);
extern lv_obj_t * ui_Main_Panel1;
extern lv_obj_t * ui_Main_Counter;
extern lv_obj_t * ui_Main_Label_Session;
extern lv_obj_t * ui_Main_Label_Location;
extern lv_obj_t * ui_Main_Label_VisualID;
// CUSTOM VARIABLES

// SCREEN: ui_Time
void ui_Time_screen_init(void);
void ui_event_Time(lv_event_t * e);
extern lv_obj_t * ui_Time;
extern lv_obj_t * ui_Time_Label_Title;
extern lv_obj_t * ui_Time_Label_Date;
extern lv_obj_t * ui_Time_Label_Time;
void ui_event_Time_SetTime(lv_event_t * e);
extern lv_obj_t * ui_Time_SetTime;
extern lv_obj_t * ui_Time_Label4;
void ui_event_Time_Sync(lv_event_t * e);
extern lv_obj_t * ui_Time_Sync;
extern lv_obj_t * ui_Time_Label1;
// CUSTOM VARIABLES

// SCREEN: ui_SetTime
void ui_SetTime_screen_init(void);
void ui_event_SetTime(lv_event_t * e);
extern lv_obj_t * ui_SetTime;
extern lv_obj_t * ui_SetTime_TabView;
extern lv_obj_t * ui_SetTime_TabPageTime;
extern lv_obj_t * ui_Time_RollerHour;
extern lv_obj_t * ui_Time_RollerMinute;
extern lv_obj_t * ui_Time_RollerAMPM;
void ui_event_SetTime_ButtonManual(lv_event_t * e);
extern lv_obj_t * ui_SetTime_ButtonManual;
extern lv_obj_t * ui_SetTime_Label5;
extern lv_obj_t * ui_SetTime_TabPageDate;
void ui_event_SetDate_ButtonManual(lv_event_t * e);
extern lv_obj_t * ui_SetDate_ButtonManual;
extern lv_obj_t * ui_SetDateLabel;
extern lv_obj_t * ui_Date_RollerDay;
void ui_event_Date_RollerYear(lv_event_t * e);
extern lv_obj_t * ui_Date_RollerYear;
void ui_event_Date_RollerMonth(lv_event_t * e);
extern lv_obj_t * ui_Date_RollerMonth;
// CUSTOM VARIABLES

// SCREEN: ui_Session
void ui_Session_screen_init(void);
void ui_event_Session(lv_event_t * e);
extern lv_obj_t * ui_Session;
void ui_event_Session_NewButton(lv_event_t * e);
extern lv_obj_t * ui_Session_NewButton;
extern lv_obj_t * ui_SessionNewButton_Label;
void ui_event_Session_ContinueButton(lv_event_t * e);
extern lv_obj_t * ui_Session_ContinueButton;
extern lv_obj_t * ui_SessionContinueButton_Label;
extern lv_obj_t * ui_Session_Roller1;
// CUSTOM VARIABLES

// SCREEN: ui_Tagging
void ui_Tagging_screen_init(void);
extern lv_obj_t * ui_Tagging;
extern lv_obj_t * ui_AddAnimal_Accept;
extern lv_obj_t * ui_AddAnimal_Label1;
extern lv_obj_t * ui_AddAnimal_Label2;
extern lv_obj_t * ui_AddAnimal_Location;
extern lv_obj_t * ui_AddAnimal_Group;
extern lv_obj_t * ui_AddAnimal_Switch1;
extern lv_obj_t * ui_AddAnimal_Label3;
extern lv_obj_t * ui_AddAnimal_RFID;
extern lv_obj_t * ui_AddAnimal_Label5;
extern lv_obj_t * ui_AddAnimal_Treatment;
// CUSTOM VARIABLES

// SCREEN: ui_Settings
void ui_Settings_screen_init(void);
void ui_event_Settings(lv_event_t * e);
extern lv_obj_t * ui_Settings;
extern lv_obj_t * ui_Settings_Label_Top;
extern lv_obj_t * ui_Settings_TabView;
extern lv_obj_t * ui_Settings_TabPageFiles;
extern lv_obj_t * ui_Settings_TextAreaFiles;
extern lv_obj_t * ui_Settings_TabPageStorage;
extern lv_obj_t * ui_Settings_TextAreaStorage;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_battery_1_bar_png);    // assets/battery_1_bar.png
LV_IMG_DECLARE(ui_img_wifi_tethering_png);    // assets/wifi_tethering.png
LV_IMG_DECLARE(ui_img_settings_png);    // assets/settings.png
LV_IMG_DECLARE(ui_img_add_circle_png);    // assets/add_circle.png
LV_IMG_DECLARE(ui_img_arrow_back_png);    // assets/arrow_back.png
LV_IMG_DECLARE(ui_img_battery_2_bar_png);    // assets/battery_2_bar.png
LV_IMG_DECLARE(ui_img_battery_3_bar_png);    // assets/battery_3_bar.png
LV_IMG_DECLARE(ui_img_battery_4_bar_png);    // assets/battery_4_bar.png
LV_IMG_DECLARE(ui_img_battery_5_bar_png);    // assets/battery_5_bar.png
LV_IMG_DECLARE(ui_img_battery_alert_png);    // assets/battery_alert.png
LV_IMG_DECLARE(ui_img_battery_charging_full_png);    // assets/battery_charging_full.png
LV_IMG_DECLARE(ui_img_battery_full_png);    // assets/battery_full.png
LV_IMG_DECLARE(ui_img_bluetooth_png);    // assets/bluetooth.png
LV_IMG_DECLARE(ui_img_bluetooth_disabled_png);    // assets/bluetooth_disabled.png
LV_IMG_DECLARE(ui_img_cancel_png);    // assets/cancel.png
LV_IMG_DECLARE(ui_img_contactless_png);    // assets/contactless.png
LV_IMG_DECLARE(ui_img_contactless_off_png);    // assets/contactless_off.png
LV_IMG_DECLARE(ui_img_sd_card_png);    // assets/sd_card.png
LV_IMG_DECLARE(
    ui_img_turn_left_200dp_1f1f1f_fill0_wght700_grad0_opsz48_png);    // assets/turn_left_200dp_1F1F1F_FILL0_wght700_GRAD0_opsz48.png
LV_IMG_DECLARE(ui_img_volume_down_png);    // assets/volume_down.png
LV_IMG_DECLARE(ui_img_volume_off_png);    // assets/volume_off.png
LV_IMG_DECLARE(ui_img_volume_up_png);    // assets/volume_up.png
LV_IMG_DECLARE(ui_img_wifi_png);    // assets/wifi.png
LV_IMG_DECLARE(ui_img_wifi_off_png);    // assets/wifi_off.png
LV_IMG_DECLARE(ui_img_wifi_tethering_off_png);    // assets/wifi_tethering_off.png

// FONTS
LV_FONT_DECLARE(ui_font_BIG);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
