// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: OTR_AMOLED_UITEST

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void mainScreenLoaded(lv_event_t * e);
void tetherClicked(lv_event_t * e);
void counterClicked(lv_event_t * e);
void timeScreenLoaded(lv_event_t * e);
void SetTimeScreenLoaded(lv_event_t * e);
void setTimeManual(lv_event_t * e);
void roller_update(lv_event_t * e);
void sessionScreenLoaded(lv_event_t * e);
void newSessionButtonPressed(lv_event_t * e);
void settingsScreenLoaded(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
