// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: OTR_AMOLED_UITEST

#include "ui.h"
#include "otrUI.h"

void timeScreenLoaded(lv_event_t * e)
{
	// Your code here
	setDateTimeOnTimeScreen();
}

void SetTimeScreenLoaded(lv_event_t * e)
{
	// Your code here
	setDateTimeRollers();
}


void setTimeManual(lv_event_t * e)
{
	// Your code here
	setTimeOrDateManualPressed();
}

void roller_update(lv_event_t * e)
{
	// Your code here
	updateDayRoller();
}

void mainScreenLoaded(lv_event_t * e)
{
	// Your code here
	updateTopPanel();
}

void tetherClicked(lv_event_t * e)
{
	// Your code here
}

void settingFilesTabSelected(lv_event_t * e)
{
	
}

void settingsScreenLoaded(lv_event_t * e)
{
	displayFileSystemContents();
	displayStorageInfo();
}

void counterClicked(lv_event_t * e)
{
	// Your code here
}

void sessionScreenLoaded(lv_event_t * e)
{
	populateSessionList();
}

void newSessionButtonPressed(lv_event_t * e)
{
	newSession();
}
