// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: OTR_AMOLED_UITEST

#include "../ui.h"

void ui_Main_screen_init(void)
{
    ui_Main = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Main, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Main_TopPanel = lv_obj_create(ui_Main);
    lv_obj_set_width(ui_Main_TopPanel, lv_pct(100));
    lv_obj_set_height(ui_Main_TopPanel, lv_pct(10));
    lv_obj_set_x(ui_Main_TopPanel, lv_pct(0));
    lv_obj_set_y(ui_Main_TopPanel, lv_pct(-45));
    lv_obj_set_align(ui_Main_TopPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Main_TopPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Main_TopPanelBattery = lv_img_create(ui_Main_TopPanel);
    lv_img_set_src(ui_Main_TopPanelBattery, &ui_img_battery_1_bar_png);
    lv_obj_set_width(ui_Main_TopPanelBattery, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Main_TopPanelBattery, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Main_TopPanelBattery, lv_pct(5));
    lv_obj_set_y(ui_Main_TopPanelBattery, lv_pct(0));
    lv_obj_set_align(ui_Main_TopPanelBattery, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Main_TopPanelBattery, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Main_TopPanelBattery, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Main_TopPanelScan = lv_img_create(ui_Main_TopPanel);
    lv_img_set_src(ui_Main_TopPanelScan, &ui_img_wifi_tethering_png);
    lv_obj_set_width(ui_Main_TopPanelScan, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Main_TopPanelScan, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Main_TopPanelScan, lv_pct(-45));
    lv_obj_set_y(ui_Main_TopPanelScan, lv_pct(0));
    lv_obj_set_align(ui_Main_TopPanelScan, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Main_TopPanelScan, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_clear_flag(ui_Main_TopPanelScan,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Main_TopPanelButtonSettings = lv_imgbtn_create(ui_Main_TopPanel);
    lv_imgbtn_set_src(ui_Main_TopPanelButtonSettings, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_settings_png, NULL);
    lv_imgbtn_set_src(ui_Main_TopPanelButtonSettings, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_settings_png, NULL);
    lv_obj_set_height(ui_Main_TopPanelButtonSettings, 48);
    lv_obj_set_width(ui_Main_TopPanelButtonSettings, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Main_TopPanelButtonSettings, lv_pct(-20));
    lv_obj_set_y(ui_Main_TopPanelButtonSettings, lv_pct(0));
    lv_obj_set_align(ui_Main_TopPanelButtonSettings, LV_ALIGN_CENTER);

    ui_Main_TopPanelButtonTime = lv_btn_create(ui_Main_TopPanel);
    lv_obj_set_height(ui_Main_TopPanelButtonTime, 48);
    lv_obj_set_width(ui_Main_TopPanelButtonTime, lv_pct(40));
    lv_obj_set_x(ui_Main_TopPanelButtonTime, lv_pct(35));
    lv_obj_set_y(ui_Main_TopPanelButtonTime, lv_pct(0));
    lv_obj_set_align(ui_Main_TopPanelButtonTime, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Main_TopPanelButtonTime, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Main_TopPanelButtonTime, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Main_TopPanelButtonTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Main_TopPanelButtonTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Main_TopPanelButtonTime, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Main_TopPanelButtonTime, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Main_TopPanelTime = lv_label_create(ui_Main_TopPanelButtonTime);
    lv_obj_set_width(ui_Main_TopPanelTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Main_TopPanelTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Main_TopPanelTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Main_TopPanelTime, "22:59");
    lv_obj_set_style_text_color(ui_Main_TopPanelTime, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Main_TopPanelTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Main_TopPanelTime, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Main_Label_Title = lv_label_create(ui_Main);
    lv_obj_set_width(ui_Main_Label_Title, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Main_Label_Title, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Main_Label_Title, lv_pct(0));
    lv_obj_set_y(ui_Main_Label_Title, lv_pct(-32));
    lv_obj_set_align(ui_Main_Label_Title, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Main_Label_Title, "OPEN TAG \nREADER");
    lv_obj_set_style_text_align(ui_Main_Label_Title, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Main_Label_Title, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Main_Label_RFID = lv_label_create(ui_Main);
    lv_obj_set_width(ui_Main_Label_RFID, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Main_Label_RFID, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Main_Label_RFID, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Main_Label_RFID, "900 123456789012");
    lv_obj_set_style_text_font(ui_Main_Label_RFID, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Main_LabelBottom = lv_label_create(ui_Main);
    lv_obj_set_width(ui_Main_LabelBottom, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Main_LabelBottom, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Main_LabelBottom, 0);
    lv_obj_set_y(ui_Main_LabelBottom, -10);
    lv_obj_set_align(ui_Main_LabelBottom, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Main_LabelBottom, "IP Address:\n1.1.1..1");
    lv_obj_set_style_text_align(ui_Main_LabelBottom, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Main_LabelBottom, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Main_Panel1 = lv_obj_create(ui_Main);
    lv_obj_set_width(ui_Main_Panel1, 234);
    lv_obj_set_height(ui_Main_Panel1, 124);
    lv_obj_set_x(ui_Main_Panel1, 0);
    lv_obj_set_y(ui_Main_Panel1, 130);
    lv_obj_set_align(ui_Main_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Main_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Main_Panel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Main_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Main_Counter = lv_label_create(ui_Main_Panel1);
    lv_obj_set_width(ui_Main_Counter, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Main_Counter, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Main_Counter, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Main_Counter, "0");
    lv_obj_add_flag(ui_Main_Counter, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_align(ui_Main_Counter, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Main_Counter, &ui_font_BIG, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Main_Label_Session = lv_label_create(ui_Main);
    lv_obj_set_width(ui_Main_Label_Session, lv_pct(90));
    lv_obj_set_height(ui_Main_Label_Session, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Main_Label_Session, lv_pct(0));
    lv_obj_set_y(ui_Main_Label_Session, lv_pct(-18));
    lv_obj_set_align(ui_Main_Label_Session, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_Main_Label_Session, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_Main_Label_Session, "Swipe right for sessions...");
    lv_obj_set_style_text_font(ui_Main_Label_Session, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Main_Label_Location = lv_label_create(ui_Main);
    lv_obj_set_width(ui_Main_Label_Location, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Main_Label_Location, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Main_Label_Location, lv_pct(0));
    lv_obj_set_y(ui_Main_Label_Location, lv_pct(-10));
    lv_obj_set_align(ui_Main_Label_Location, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Main_Label_Location, "Location");
    lv_obj_set_style_text_font(ui_Main_Label_Location, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Main_Label_VisualID = lv_label_create(ui_Main);
    lv_obj_set_width(ui_Main_Label_VisualID, lv_pct(90));
    lv_obj_set_height(ui_Main_Label_VisualID, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Main_Label_VisualID, lv_pct(0));
    lv_obj_set_y(ui_Main_Label_VisualID, lv_pct(8));
    lv_obj_set_align(ui_Main_Label_VisualID, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_Main_Label_VisualID, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_Main_Label_VisualID, "VISUAL ID");
    lv_label_set_recolor(ui_Main_Label_VisualID, "true");
    lv_obj_set_style_text_color(ui_Main_Label_VisualID, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Main_Label_VisualID, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Main_Label_VisualID, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Main_Label_VisualID, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Main_Label_VisualID, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Main_Label_VisualID, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Main_TopPanelScan, ui_event_Main_TopPanelScan, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Main_TopPanelButtonSettings, ui_event_Main_TopPanelButtonSettings, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Main_TopPanelButtonTime, ui_event_Main_TopPanelButtonTime, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Main_Panel1, ui_event_Main_Panel1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Main, ui_event_Main, LV_EVENT_ALL, NULL);

}
