// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: OTR_AMOLED_UITEST

#include "../ui.h"

void ui_Records_screen_init(void)
{
    ui_Records = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Records, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Records_TabView1 = lv_tabview_create(ui_Records, LV_DIR_TOP, 75);
    lv_obj_set_width(ui_Records_TabView1, lv_pct(100));
    lv_obj_set_height(ui_Records_TabView1, lv_pct(100));
    lv_obj_set_align(ui_Records_TabView1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Records_TabView1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_set_style_text_font(lv_tabview_get_tab_btns(ui_Records_TabView1), &lv_font_montserrat_26,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Records_TabRecord = lv_tabview_add_tab(ui_Records_TabView1, "RECORD");

    ui_Record_DropdownType = lv_dropdown_create(ui_Records_TabRecord);
    lv_dropdown_set_options(ui_Record_DropdownType, "Type1\nType2\nType3");
    lv_dropdown_set_text(ui_Record_DropdownType, "Type");
    lv_obj_set_width(ui_Record_DropdownType, lv_pct(100));
    lv_obj_set_height(ui_Record_DropdownType, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Record_DropdownType, lv_pct(0));
    lv_obj_set_y(ui_Record_DropdownType, lv_pct(-30));
    lv_obj_set_align(ui_Record_DropdownType, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Record_DropdownType, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_Record_DropdownType, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_Record_DropdownType), &lv_font_montserrat_34,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_Record_DropdownType), &lv_font_montserrat_34,
                               LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Record_DropdownGroup = lv_dropdown_create(ui_Records_TabRecord);
    lv_dropdown_set_options(ui_Record_DropdownGroup, "Group1\nGroup2\nGroup3");
    lv_dropdown_set_text(ui_Record_DropdownGroup, "Group");
    lv_obj_set_width(ui_Record_DropdownGroup, lv_pct(100));
    lv_obj_set_height(ui_Record_DropdownGroup, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Record_DropdownGroup, lv_pct(0));
    lv_obj_set_y(ui_Record_DropdownGroup, lv_pct(-15));
    lv_obj_set_align(ui_Record_DropdownGroup, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Record_DropdownGroup, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_Record_DropdownGroup, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_Record_DropdownGroup), &lv_font_montserrat_34,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_Record_DropdownGroup), &lv_font_montserrat_34,
                               LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Record_DropdownStatus = lv_dropdown_create(ui_Records_TabRecord);
    lv_dropdown_set_options(ui_Record_DropdownStatus, "Group1\nGroup2\nGroup3");
    lv_dropdown_set_text(ui_Record_DropdownStatus, "Status");
    lv_obj_set_width(ui_Record_DropdownStatus, lv_pct(100));
    lv_obj_set_height(ui_Record_DropdownStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Record_DropdownStatus, lv_pct(0));
    lv_obj_set_y(ui_Record_DropdownStatus, lv_pct(-45));
    lv_obj_set_align(ui_Record_DropdownStatus, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Record_DropdownStatus, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_Record_DropdownStatus, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_Record_DropdownStatus), &lv_font_montserrat_34,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_Record_DropdownStatus), &lv_font_montserrat_34,
                               LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Record_DropdownLocation = lv_dropdown_create(ui_Records_TabRecord);
    lv_dropdown_set_options(ui_Record_DropdownLocation, "Location1\nLocation2\nLocation3");
    lv_dropdown_set_text(ui_Record_DropdownLocation, "Location");
    lv_obj_set_width(ui_Record_DropdownLocation, lv_pct(100));
    lv_obj_set_height(ui_Record_DropdownLocation, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Record_DropdownLocation, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Record_DropdownLocation, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_Record_DropdownLocation, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_Record_DropdownLocation), &lv_font_montserrat_34,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_Record_DropdownLocation), &lv_font_montserrat_34,
                               LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Record_LabelGender = lv_label_create(ui_Records_TabRecord);
    lv_obj_set_width(ui_Record_LabelGender, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Record_LabelGender, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Record_LabelGender, lv_pct(0));
    lv_obj_set_y(ui_Record_LabelGender, lv_pct(15));
    lv_obj_set_align(ui_Record_LabelGender, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Record_LabelGender, "Gender");
    lv_obj_set_style_text_font(ui_Record_LabelGender, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Record_LabelWeight = lv_label_create(ui_Records_TabRecord);
    lv_obj_set_width(ui_Record_LabelWeight, lv_pct(100));
    lv_obj_set_height(ui_Record_LabelWeight, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_x(ui_Record_LabelWeight, lv_pct(0));
    lv_obj_set_y(ui_Record_LabelWeight, lv_pct(35));
    lv_obj_set_align(ui_Record_LabelWeight, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Record_LabelWeight, "Weight: ##kg");
    lv_obj_set_style_text_align(ui_Record_LabelWeight, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Record_LabelWeight, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Records_TabTag = lv_tabview_add_tab(ui_Records_TabView1, "TAG");

    ui_Tag_DropdownStatus = lv_dropdown_create(ui_Records_TabTag);
    lv_dropdown_set_options(ui_Tag_DropdownStatus, "Group1\nGroup2\nGroup3");
    lv_dropdown_set_text(ui_Tag_DropdownStatus, "Status");
    lv_obj_set_width(ui_Tag_DropdownStatus, lv_pct(100));
    lv_obj_set_height(ui_Tag_DropdownStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Tag_DropdownStatus, lv_pct(0));
    lv_obj_set_y(ui_Tag_DropdownStatus, lv_pct(-45));
    lv_obj_set_align(ui_Tag_DropdownStatus, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Tag_DropdownStatus, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_Tag_DropdownStatus, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_Tag_DropdownStatus), &lv_font_montserrat_34,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_Tag_DropdownStatus), &lv_font_montserrat_34,
                               LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Records_Label3 = lv_label_create(ui_Records_TabTag);
    lv_obj_set_width(ui_Records_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Records_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Records_Label3, lv_pct(-36));
    lv_obj_set_y(ui_Records_Label3, lv_pct(-32));
    lv_obj_set_align(ui_Records_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Records_Label3, "RFID:");
    lv_obj_set_style_text_font(ui_Records_Label3, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Records_Label_RFID = lv_label_create(ui_Records_TabTag);
    lv_obj_set_width(ui_Records_Label_RFID, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Records_Label_RFID, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Records_Label_RFID, lv_pct(0));
    lv_obj_set_y(ui_Records_Label_RFID, lv_pct(-25));
    lv_obj_set_align(ui_Records_Label_RFID, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Records_Label_RFID, "900 123456789012");
    lv_obj_set_style_text_font(ui_Records_Label_RFID, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Records_Label1 = lv_label_create(ui_Records_TabTag);
    lv_obj_set_width(ui_Records_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Records_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Records_Label1, lv_pct(-40));
    lv_obj_set_y(ui_Records_Label1, lv_pct(-15));
    lv_obj_set_align(ui_Records_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Records_Label1, "PIC:");
    lv_obj_set_style_text_font(ui_Records_Label1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Records_Label_PIC = lv_label_create(ui_Records_TabTag);
    lv_obj_set_width(ui_Records_Label_PIC, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Records_Label_PIC, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Records_Label_PIC, lv_pct(10));
    lv_obj_set_y(ui_Records_Label_PIC, lv_pct(-15));
    lv_obj_set_align(ui_Records_Label_PIC, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Records_Label_PIC, "NK509384");
    lv_obj_set_style_text_font(ui_Records_Label_PIC, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Records_Label2 = lv_label_create(ui_Records_TabTag);
    lv_obj_set_width(ui_Records_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Records_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Records_Label2, lv_pct(-30));
    lv_obj_set_y(ui_Records_Label2, lv_pct(-5));
    lv_obj_set_align(ui_Records_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Records_Label2, "NLISID:");
    lv_obj_set_style_text_font(ui_Records_Label2, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Records_Label_NLISID = lv_label_create(ui_Records_TabTag);
    lv_obj_set_width(ui_Records_Label_NLISID, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Records_Label_NLISID, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Records_Label_NLISID, lv_pct(-2));
    lv_obj_set_y(ui_Records_Label_NLISID, lv_pct(4));
    lv_obj_set_align(ui_Records_Label_NLISID, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Records_Label_NLISID, "NK509384ASU00001");
    lv_obj_set_style_text_font(ui_Records_Label_NLISID, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Records_Label4 = lv_label_create(ui_Records_TabTag);
    lv_obj_set_width(ui_Records_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Records_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Records_Label4, lv_pct(-30));
    lv_obj_set_y(ui_Records_Label4, lv_pct(21));
    lv_obj_set_align(ui_Records_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Records_Label4, "Colour:");
    lv_obj_set_style_text_font(ui_Records_Label4, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Records_Label_Colour = lv_label_create(ui_Records_TabTag);
    lv_obj_set_width(ui_Records_Label_Colour, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Records_Label_Colour, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Records_Label_Colour, lv_pct(21));
    lv_obj_set_y(ui_Records_Label_Colour, lv_pct(21));
    lv_obj_set_align(ui_Records_Label_Colour, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Records_Label_Colour, "Yellow");
    lv_obj_set_style_text_font(ui_Records_Label_Colour, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Records_Label5 = lv_label_create(ui_Records_TabTag);
    lv_obj_set_width(ui_Records_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Records_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Records_Label5, lv_pct(-32));
    lv_obj_set_y(ui_Records_Label5, lv_pct(12));
    lv_obj_set_align(ui_Records_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Records_Label5, "Vis ID:");
    lv_obj_set_style_text_font(ui_Records_Label5, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Records_Label_VisualID = lv_label_create(ui_Records_TabTag);
    lv_obj_set_width(ui_Records_Label_VisualID, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Records_Label_VisualID, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Records_Label_VisualID, lv_pct(21));
    lv_obj_set_y(ui_Records_Label_VisualID, lv_pct(12));
    lv_obj_set_align(ui_Records_Label_VisualID, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Records_Label_VisualID, "CHAD 001");
    lv_obj_set_style_text_font(ui_Records_Label_VisualID, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Records, ui_event_Records, LV_EVENT_ALL, NULL);

}
