// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: OTR_AMOLED_UITEST

#include "../ui.h"

void ui_Session_screen_init(void)
{
    ui_Session = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Session, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Session_NewButton = lv_btn_create(ui_Session);
    lv_obj_set_width(ui_Session_NewButton, lv_pct(90));
    lv_obj_set_height(ui_Session_NewButton, lv_pct(15));
    lv_obj_set_x(ui_Session_NewButton, lv_pct(0));
    lv_obj_set_y(ui_Session_NewButton, lv_pct(-40));
    lv_obj_set_align(ui_Session_NewButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Session_NewButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Session_NewButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SessionNewButton_Label = lv_label_create(ui_Session_NewButton);
    lv_obj_set_width(ui_SessionNewButton_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SessionNewButton_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SessionNewButton_Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SessionNewButton_Label, "NEW");
    lv_obj_set_style_text_font(ui_SessionNewButton_Label, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Session_ContinueButton = lv_btn_create(ui_Session);
    lv_obj_set_width(ui_Session_ContinueButton, lv_pct(90));
    lv_obj_set_height(ui_Session_ContinueButton, lv_pct(15));
    lv_obj_set_x(ui_Session_ContinueButton, lv_pct(0));
    lv_obj_set_y(ui_Session_ContinueButton, lv_pct(-20));
    lv_obj_set_align(ui_Session_ContinueButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Session_ContinueButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Session_ContinueButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SessionContinueButton_Label = lv_label_create(ui_Session_ContinueButton);
    lv_obj_set_width(ui_SessionContinueButton_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SessionContinueButton_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SessionContinueButton_Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SessionContinueButton_Label, "CONT...");
    lv_obj_set_style_text_font(ui_SessionContinueButton_Label, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Session_Roller1 = lv_roller_create(ui_Session);
    lv_roller_set_options(ui_Session_Roller1, "Option 1\nOption 2\nOption 3", LV_ROLLER_MODE_INFINITE);
    lv_obj_set_width(ui_Session_Roller1, lv_pct(90));
    lv_obj_set_height(ui_Session_Roller1, lv_pct(45));
    lv_obj_set_x(ui_Session_Roller1, lv_pct(0));
    lv_obj_set_y(ui_Session_Roller1, lv_pct(15));
    lv_obj_set_align(ui_Session_Roller1, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_Session, ui_event_Session, LV_EVENT_ALL, NULL);

}
