// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: OTR_AMOLED_UITEST

#include "../ui.h"

void ui_Settings_screen_init(void)
{
    ui_Settings = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Settings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Settings_Label_Top = lv_label_create(ui_Settings);
    lv_obj_set_width(ui_Settings_Label_Top, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Settings_Label_Top, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Settings_Label_Top, lv_pct(0));
    lv_obj_set_y(ui_Settings_Label_Top, lv_pct(-46));
    lv_obj_set_align(ui_Settings_Label_Top, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Settings_Label_Top, "Settings");
    lv_obj_set_style_text_font(ui_Settings_Label_Top, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

}
