// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: OTR_AMOLED_UITEST

#include "../ui.h"

void ui_Time_screen_init(void)
{
    ui_Time = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Time, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Time_Label_Title = lv_label_create(ui_Time);
    lv_obj_set_width(ui_Time_Label_Title, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Time_Label_Title, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Time_Label_Title, lv_pct(0));
    lv_obj_set_y(ui_Time_Label_Title, lv_pct(2));
    lv_obj_set_align(ui_Time_Label_Title, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Time_Label_Title, "SET TIME");
    lv_obj_set_style_text_align(ui_Time_Label_Title, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Time_Label_Title, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Time_Label_Date = lv_label_create(ui_Time);
    lv_obj_set_width(ui_Time_Label_Date, lv_pct(90));
    lv_obj_set_height(ui_Time_Label_Date, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Time_Label_Date, lv_pct(0));
    lv_obj_set_y(ui_Time_Label_Date, lv_pct(-25));
    lv_obj_set_align(ui_Time_Label_Date, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Time_Label_Date, "29/12/2024");
    lv_obj_set_style_text_align(ui_Time_Label_Date, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Time_Label_Date, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Time_Label_Time = lv_label_create(ui_Time);
    lv_obj_set_width(ui_Time_Label_Time, lv_pct(90));
    lv_obj_set_height(ui_Time_Label_Time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Time_Label_Time, lv_pct(0));
    lv_obj_set_y(ui_Time_Label_Time, lv_pct(-10));
    lv_obj_set_align(ui_Time_Label_Time, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Time_Label_Time, "12:34 PM");
    lv_obj_set_style_text_align(ui_Time_Label_Time, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Time_Label_Time, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Time_SetTime = lv_btn_create(ui_Time);
    lv_obj_set_width(ui_Time_SetTime, lv_pct(90));
    lv_obj_set_height(ui_Time_SetTime, lv_pct(15));
    lv_obj_set_x(ui_Time_SetTime, lv_pct(0));
    lv_obj_set_y(ui_Time_SetTime, lv_pct(10));
    lv_obj_set_align(ui_Time_SetTime, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Time_SetTime, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Time_SetTime, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Time_Label4 = lv_label_create(ui_Time_SetTime);
    lv_obj_set_width(ui_Time_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Time_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Time_Label4, 5);
    lv_obj_set_y(ui_Time_Label4, 2);
    lv_obj_set_align(ui_Time_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Time_Label4, "SET");
    lv_obj_set_style_text_font(ui_Time_Label4, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Time_Sync = lv_btn_create(ui_Time);
    lv_obj_set_width(ui_Time_Sync, lv_pct(90));
    lv_obj_set_height(ui_Time_Sync, lv_pct(15));
    lv_obj_set_x(ui_Time_Sync, lv_pct(0));
    lv_obj_set_y(ui_Time_Sync, lv_pct(30));
    lv_obj_set_align(ui_Time_Sync, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Time_Sync, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Time_Sync, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Time_Label1 = lv_label_create(ui_Time_Sync);
    lv_obj_set_width(ui_Time_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Time_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Time_Label1, 5);
    lv_obj_set_y(ui_Time_Label1, 2);
    lv_obj_set_align(ui_Time_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Time_Label1, "SYNC");
    lv_obj_set_style_text_font(ui_Time_Label1, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Time_SetTime, ui_event_Time_SetTime, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Time_Sync, ui_event_Time_Sync, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Time, ui_event_Time, LV_EVENT_ALL, NULL);

}
