// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: OTR_AMOLED_UITEST

#include "../ui.h"

void ui_Tagging_screen_init(void)
{
    ui_Tagging = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Tagging, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AddAnimal_Accept = lv_btn_create(ui_Tagging);
    lv_obj_set_width(ui_AddAnimal_Accept, lv_pct(80));
    lv_obj_set_height(ui_AddAnimal_Accept, lv_pct(15));
    lv_obj_set_x(ui_AddAnimal_Accept, lv_pct(0));
    lv_obj_set_y(ui_AddAnimal_Accept, lv_pct(37));
    lv_obj_set_align(ui_AddAnimal_Accept, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AddAnimal_Accept, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_AddAnimal_Accept, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AddAnimal_Label1 = lv_label_create(ui_AddAnimal_Accept);
    lv_obj_set_width(ui_AddAnimal_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AddAnimal_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AddAnimal_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AddAnimal_Label1, "Activate");
    lv_obj_set_style_text_font(ui_AddAnimal_Label1, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AddAnimal_Label2 = lv_label_create(ui_Tagging);
    lv_obj_set_width(ui_AddAnimal_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AddAnimal_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AddAnimal_Label2, lv_pct(0));
    lv_obj_set_y(ui_AddAnimal_Label2, lv_pct(-46));
    lv_obj_set_align(ui_AddAnimal_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AddAnimal_Label2, "Activate Tag");
    lv_obj_set_style_text_font(ui_AddAnimal_Label2, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AddAnimal_Location = lv_dropdown_create(ui_Tagging);
    lv_dropdown_set_options(ui_AddAnimal_Location, "Dorethea\nBellevue Cl\n");
    lv_dropdown_set_text(ui_AddAnimal_Location, "Dorethea");
    lv_obj_set_width(ui_AddAnimal_Location, lv_pct(90));
    lv_obj_set_height(ui_AddAnimal_Location, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AddAnimal_Location, lv_pct(0));
    lv_obj_set_y(ui_AddAnimal_Location, lv_pct(-35));
    lv_obj_set_align(ui_AddAnimal_Location, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AddAnimal_Location, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_AddAnimal_Location, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_AddAnimal_Group = lv_dropdown_create(ui_Tagging);
    lv_dropdown_set_options(ui_AddAnimal_Group,
                            "Lamb 1st Vaccine\nLambs\nEwes Level 1\nMaiden Ewes\nCulls\nEwes Level 2\nEwes Level 3\nRams");
    lv_dropdown_set_text(ui_AddAnimal_Group, "Group ...");
    lv_obj_set_width(ui_AddAnimal_Group, lv_pct(90));
    lv_obj_set_height(ui_AddAnimal_Group, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AddAnimal_Group, lv_pct(0));
    lv_obj_set_y(ui_AddAnimal_Group, lv_pct(-25));
    lv_obj_set_align(ui_AddAnimal_Group, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AddAnimal_Group, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_AddAnimal_Group, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_AddAnimal_Switch1 = lv_switch_create(ui_Tagging);
    lv_obj_set_width(ui_AddAnimal_Switch1, lv_pct(80));
    lv_obj_set_height(ui_AddAnimal_Switch1, lv_pct(20));
    lv_obj_set_x(ui_AddAnimal_Switch1, lv_pct(0));
    lv_obj_set_y(ui_AddAnimal_Switch1, lv_pct(5));
    lv_obj_set_align(ui_AddAnimal_Switch1, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_AddAnimal_Switch1, lv_color_hex(0xFA94F3), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AddAnimal_Switch1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_AddAnimal_Label3 = lv_label_create(ui_Tagging);
    lv_obj_set_width(ui_AddAnimal_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AddAnimal_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AddAnimal_Label3, 3);
    lv_obj_set_y(ui_AddAnimal_Label3, 24);
    lv_obj_set_align(ui_AddAnimal_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AddAnimal_Label3, "F    M");
    lv_obj_set_style_text_font(ui_AddAnimal_Label3, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AddAnimal_RFID = lv_label_create(ui_Tagging);
    lv_obj_set_width(ui_AddAnimal_RFID, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AddAnimal_RFID, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AddAnimal_RFID, lv_pct(0));
    lv_obj_set_y(ui_AddAnimal_RFID, lv_pct(20));
    lv_obj_set_align(ui_AddAnimal_RFID, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AddAnimal_RFID, "900 123456789012");

    ui_AddAnimal_Label5 = lv_label_create(ui_Tagging);
    lv_obj_set_width(ui_AddAnimal_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AddAnimal_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AddAnimal_Label5, lv_pct(0));
    lv_obj_set_y(ui_AddAnimal_Label5, lv_pct(25));
    lv_obj_set_align(ui_AddAnimal_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AddAnimal_Label5, "CHAD 002");
    lv_obj_set_style_text_font(ui_AddAnimal_Label5, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AddAnimal_Treatment = lv_dropdown_create(ui_Tagging);
    lv_dropdown_set_options(ui_AddAnimal_Treatment, "Glanvac 6-1 1mL");
    lv_dropdown_set_text(ui_AddAnimal_Treatment, "Treatment ...");
    lv_obj_set_width(ui_AddAnimal_Treatment, lv_pct(90));
    lv_obj_set_height(ui_AddAnimal_Treatment, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AddAnimal_Treatment, lv_pct(0));
    lv_obj_set_y(ui_AddAnimal_Treatment, lv_pct(-15));
    lv_obj_set_align(ui_AddAnimal_Treatment, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AddAnimal_Treatment, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_AddAnimal_Treatment, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);


    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_AddAnimal_Treatment), &lv_font_montserrat_20,
                               LV_PART_SELECTED | LV_STATE_DEFAULT);

}
